### ISSUE TITLE
Download link doesnt work

### ISSUE THREAD

**Issue by kscheirer** [achieve-internet/wsdl_docs#12]
After rendering a WSDL file, I see a download link when viewing an operation.

The html for the link is:
`<span class="wsdl-file"><a href="/private%3A//wsdl_docs_files/KPCCgetCoverages.wsdl">View raw WSDL XML</a></span>`

Which returns a 404 from Drupal. I think the filestream wrapper `private://` needs to be converted to a file uri.

**Comment by AlexBorsody** [comment]
This was done as part of feedback I didn't write this.

**Comment by kbrinner** [comment]
Fixed - see
14d2743e GAK-56: allow users to download zip if available
3641f12f GAK-59: add permission to download WSDL files, implment hook_file_download()
cf9ede64 GAK-56: add link to download any file (archive or single) uploaded for service
